# Run all our tests
# include("compat.jl")
# include("archive_utils.jl")
# include("dependencies.jl")
# include("platforms.jl")
# include("prefix.jl")
# include("products.jl")
# include("sources.jl")
# include("rootfs.jl")
include("runners.jl")
